# Generated by Django 4.2.20 on 2025-08-19 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Envio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_guia", models.CharField(max_length=20, unique=True)),
                (
                    "estado_actual",
                    models.CharField(
                        choices=[
                            ("RECIBIDO", "Recibido"),
                            ("EN_TRANSITO", "En tránsito"),
                            ("EN_REPARTO", "En reparto"),
                            ("ENTREGADO", "Entregado"),
                            ("DEVUELTO", "Devuelto"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="RECIBIDO",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "fecha_estimada_entrega",
                    models.DateField(blank=True, null=True),
                ),
                ("descripcion", models.TextField()),
                (
                    "peso",
                    models.DecimalField(
                        decimal_places=2, help_text="Peso en kg", max_digits=6
                    ),
                ),
                (
                    "valor_declarado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("remitente_nombre", models.CharField(max_length=100)),
                ("remitente_direccion", models.TextField()),
                ("remitente_telefono", models.CharField(max_length=20)),
                (
                    "remitente_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("destinatario_nombre", models.CharField(max_length=100)),
                ("destinatario_direccion", models.TextField()),
                ("destinatario_telefono", models.CharField(max_length=20)),
                (
                    "destinatario_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Envío",
                "verbose_name_plural": "Envíos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="HistorialEstado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("RECIBIDO", "Recibido"),
                            ("EN_TRANSITO", "En tránsito"),
                            ("EN_REPARTO", "En reparto"),
                            ("ENTREGADO", "Entregado"),
                            ("DEVUELTO", "Devuelto"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comentario", models.TextField(blank=True, null=True)),
                (
                    "ubicacion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "envio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="envios.envio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Estado",
                "verbose_name_plural": "Historial de Estados",
                "ordering": ["-fecha"],
            },
        ),
    ]
