# Generated by Django 4.2.20 on 2025-08-26 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("envios", "0001_initial"),
        ("empresas", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historialestado",
            name="registrado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="envio",
            name="actualizado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="envios_actualizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="envio",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="envios_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="envio",
            name="empresa",
            field=models.ForeignKey(
                help_text="Empresa propietaria del envío",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="envios",
                to="empresas.empresa",
            ),
        ),
    ]
