# Generated by Django 4.2.20 on 2025-08-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("envios", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envio",
            name="peso",
            field=models.DecimalField(
                decimal_places=2, help_text="Peso en libras", max_digits=6
            ),
        ),
    ]
