# Generated by Django 4.2.23 on 2025-08-20 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_fix_usuario_relation'),
        ('envios', '0003_add_empresa_to_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa propietaria del envío', on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='empresas.empresa'),
        ),
    ]
