# Generated by Django 4.2.20 on 2025-08-26 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Identificador único para URLs",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("ruc", models.CharField(blank=True, max_length=20, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Empresa activa en el sistema"
                    ),
                ),
                (
                    "dominio",
                    models.CharField(
                        blank=True,
                        help_text="Dominio personalizado (futuro)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "configuracion",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuraciones específicas de la empresa",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("ultima_actualizacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("admin_empresa", "Administrador de Empresa"),
                            ("operador_miami", "Operador Miami"),
                            ("operador_cuba", "Operador Cuba"),
                            ("remitente", "Remitente"),
                            ("destinatario", "Destinatario"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Usuario activo en la empresa"
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("fecha_vinculacion", models.DateTimeField(auto_now_add=True)),
                ("ultima_actividad", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios",
                        to="empresas.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuarios",
                "ordering": ["empresa__nombre", "rol", "usuario__first_name"],
            },
        ),
    ]
