# Generated by Django 4.2.23 on 2025-08-20 23:13

from django.db import migrations
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteUsuario',
            fields=[
            ],
            options={
                'verbose_name': '👤 Cliente',
                'verbose_name_plural': '👤 Clientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.usuario',),
            managers=[
                ('objects', usuarios.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PersonalEmpresa',
            fields=[
            ],
            options={
                'verbose_name': '👥 Personal de Empresa',
                'verbose_name_plural': '👥 Personal de Empresa',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('usuarios.usuario',),
            managers=[
                ('objects', usuarios.models.CustomUserManager()),
            ],
        ),
    ]
