# Generated by Django 4.2.21 on 2025-05-15 18:43

from django.db import migrations
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', usuarios.models.CustomUserManager()),
            ],
        ),
    ]
